apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "greenbelt-sync-server.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "greenbelt-sync-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
