image:
  repository: 563057296362.dkr.ecr.ap-northeast-2.amazonaws.com/greenbelt-profile-page-syncer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

namespace: greenbelt
