apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "greenbelt-sync-cronjob.fullname" . }}
  labels:
    {{- include "greenbelt-sync-cronjob.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - http://greenbelt.api.suhwan.dev/sync
          restartPolicy: OnFailure
